apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-buster
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-pv
          mountPath: /data
        resources:
          requests:
            cpu: 250m
            memory: 4Gi
          limits:
            cpu: 2
            memory: 12Gi
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
