apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ilb-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    service.beta.kubernetes.io/load-balancer-source-ranges: "10.140.0.0/16, 10.0.0.0/8"
  labels:
    app: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - port: 6379
