apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisinsight
  name: redisinsight
spec:
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          
